
spring:
  application:
    name: standalone-app
  task:
    scheduling:
      pool:
        size: 10 #spring by default single threaded for schedulers
  mail:
    host: smtp.gmail.com
    username: venkat9.veerareddy@gmail.com  #from email
    #generate gmail password
    password: xxxxxxxxxxx
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:emp
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    #hibernate:
    #ddl-auto: none #after setting as "none" schema.sql and data.sql can be used
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
    #ddl-auto: update

cron:
  expression:
    value: 0 0 20 * * MON  #Runs every day at 8 PM, every Monday
    value2: 0 0 20 * * MON-FRI  #Runs every day at 8 PM, excluding Saturdays and Sundays
