
spring:
  application:
    name: my-spring-jpa
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:customer
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    #hibernate:
      #ddl-auto: none #after setting as "none" schema.sql and data.sql can be used
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate:
      #ddl-auto: update

